export const markets = [
  {
    instrumentId: 'BCH',
    name: 'Bitcoin Cash',
    id: 'BCHUSD',
    volume: '5514',
    meta: {
      faq: '',
      blog: '',
      icon: 'BCH',
      forum: '',
      github: 'https://github.com/cpacia/BitcoinCash-Wallet',
      reddit: 'https://www.reddit.com/r/Bitcoincash/',
      devDocs: 'https://www.bitcoincash.org/developers',
      roadmap: '',
      summary: '',
      explorer: 'https://blockchair.com/bitcoin-cash/blocks',
      website2: '',
      explorer2: 'http://blockdozer.com/insight/',
      wikipedia: 'https://en.wikipedia.org/wiki/Bitcoin_Cash',
      foundation: '',
      whitepaper: '',
      eveningstarUrl: 'https://eveningstar.io/asset/bitcoin-cash/',
      walletDownload: '',
      teamInformation: '',
      name: 'Bitcoin Cash'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: true
  },
  {
    instrumentId: 'LTC',
    name: 'Litecoin',
    id: 'LTCUSD',
    volume: '67561',
    meta: {
      faq: '',
      blog: 'https://litecoinblog.org/',
      icon: 'LTC',
      forum: 'https://litecointalk.io/',
      github: 'https://github.com/litecoin-project/litecoin',
      reddit: 'https://www.reddit.com/r/litecoin/',
      devDocs: '',
      roadmap: 'https://litecoincore.org/',
      summary:
        'Litecoin is a peer-to-peer Internet currency that enables instant, near-zero cost payments to anyone in the world.',
      explorer: 'http://explorer.litecoin.net/chain/Litecoin',
      website2: 'https://litecoin.org/',
      explorer2: 'https://chainz.cryptoid.info/ltc/',
      wikipedia: 'https://en.wikipedia.org/wiki/Litecoin',
      foundation: 'https://litecoin-foundation.org/',
      whitepaper: '',
      eveningstarUrl: 'https://eveningstar.io/asset/litecoin/',
      walletDownload: 'https://litecoin.org/',
      teamInformation: 'https://litecoin.info/People',
      name: 'Litecoin'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: true
  },
  {
    instrumentId: 'REP',
    name: 'Augur',
    id: 'REPUSD',
    volume: '953',
    meta: {
      faq: 'http://blog.augur.net/faq-frequently-asked-questions/',
      blog: 'https://medium.com/@augurproject',
      icon: 'REP',
      forum: '',
      github: '',
      reddit: 'https://www.reddit.com/r/Augur/',
      devDocs: 'http://docs.augur.net/',
      roadmap:
        'https://medium.com/@AugurProject/a-roadmap-for-augur-and-whats-next-930fe6c7f75a',
      summary: '',
      explorer: 'https://etherscan.io/token/REP',
      website2: '',
      explorer2: '',
      wikipedia: 'https://en.wikipedia.org/wiki/Augur_(software)',
      foundation: '',
      whitepaper: 'https://www.chiefdelphi.com/media/papers/download/4141',
      eveningstarUrl: 'https://eveningstar.io/asset/augur/',
      walletDownload: '',
      teamInformation: 'http://blog.augur.net/author/augurteam/',
      name: 'Augur'
    },
    currencyCode: 'USD',
    precision: 3,
    sharePrecision: 3,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'AVT',
    name: 'Aventus',
    id: 'AVTUSD',
    volume: '8113',
    meta: {
      faq: '',
      blog: '',
      icon: 'AVT',
      forum: '',
      github: '',
      reddit: '',
      devDocs: '',
      roadmap: '',
      summary: '',
      explorer: '',
      website2: '',
      explorer2: '',
      wikipedia: '',
      foundation: '',
      whitepaper: '',
      eveningstarUrl: '',
      walletDownload: '',
      teamInformation: '',
      name: 'Aventus'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 2,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'DASH',
    name: 'Dash',
    id: 'DASHUSD',
    volume: '21991',
    meta: {
      faq: 'https://www.dash.com.sg/faqs/',
      blog: 'https://www.dash.org/blog/',
      icon: 'DASH',
      forum: 'https://www.dash.org/forum/',
      github: 'https://github.com/dashpay/dash',
      reddit: 'https://www.reddit.com/r/dashpay/',
      devDocs: '',
      roadmap: '',
      summary:
        'Use Dash to make instant, private payments online or in-store using our secure open-source platform hosted by thousands of users around the world.',
      explorer: 'https://chainz.cryptoid.info/dash/',
      website2: '',
      explorer2: '',
      wikipedia: 'https://en.wikipedia.org/wiki/Dash_(cryptocurrency)',
      foundation: 'https://www.dashfoundation.io/',
      whitepaper:
        'https://www.dash.org/wp-content/uploads/2015/04/Dash-WhitepaperV1.pdf',
      eveningstarUrl: 'https://eveningstar.io/asset/dash/',
      walletDownload: '',
      teamInformation: 'https://www.dash.org/team/',
      name: 'Dash'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'EOS',
    name: 'EOS',
    id: 'EOSUSD',
    volume: '5583717',
    meta: {
      faq: 'https://eos.io/faq.html',
      blog: 'https://eos.org/blogs',
      icon: 'EOS',
      forum: '',
      github: 'https://github.com/eosio',
      reddit: 'https://www.reddit.com/r/eos/',
      devDocs: 'http://help.ecrion.com/EOSDeveloperGuide/',
      roadmap: '',
      summary: '',
      explorer:
        'https://etherscan.io/token/0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0',
      website2: '',
      explorer2:
        'https://ethplorer.io/address/0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0',
      wikipedia: '',
      foundation: '',
      whitepaper:
        'https://github.com/EOSIO/Documentation/blob/master/TechnicalWhitePaper.md',
      eveningstarUrl: 'https://eveningstar.io/asset/eos/',
      walletDownload: '',
      teamInformation:
        'https://eveningstar.io/asset/eos/www.eos-eu.com/?Page=team',
      name: 'EOS'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'ETC',
    name: 'Ethereum Classic',
    id: 'ETCUSD',
    volume: '226773',
    meta: {
      faq: '',
      blog: '',
      icon: 'ETC',
      forum: '',
      github: 'https://github.com/ethereumclassic',
      reddit: 'https://www.reddit.com/r/EthereumClassic/',
      devDocs: '',
      roadmap: 'http://www.etcdevteam.com/roadmap.html',
      summary:
        "Ethereum Classic is a decentralized platform that runs smart contracts: applications that run exactly as programmed without any possibility of downtime, censorship, fraud or third party interference. It is a continuation of the original Ethereum blockchain - the classic 'unforked' version; free from external interference and subjective tampering of transactions.",
      explorer: 'http://gastracker.io/',
      website2: '',
      explorer2: '',
      wikipedia: 'https://en.wikipedia.org/wiki/Ethereum_Classic',
      foundation: '',
      whitepaper: '',
      eveningstarUrl: 'https://eveningstar.io/asset/ethereum-classic/',
      walletDownload: '',
      teamInformation: '',
      name: 'Ethereum Classic'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'ETP',
    name: 'Metaverse ETP',
    id: 'ETPUSD',
    volume: '173056',
    meta: {
      faq: '',
      blog: 'https://blog.mvs.live/',
      icon: 'ETP',
      forum: 'https://metaversetalk.org/forum.php',
      github: 'https://github.com/mvs-org',
      reddit: '',
      devDocs:
        'https://github.com/mvs-org/metaverse/wiki/Metaverse-API-Call-List',
      roadmap: '',
      summary:
        'Metaverse ETP (ETP, also known as Entropy) is the token that powers the Metaverse platform through its function as collateral and value measurement.',
      explorer: 'https://explorer.mvs.live/',
      website2: '',
      explorer2: '',
      wikipedia: '',
      foundation: '',
      whitepaper:
        'https://mvs.org/attachment/Metaverse-Whitepaper-english-draft.pdf',
      eveningstarUrl: 'https://eveningstar.io/asset/metaverse/',
      walletDownload: 'https://mvs.org/#download',
      teamInformation: '',
      name: 'Metaverse ETP'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'XMR',
    name: 'Monero',
    id: 'XMRUSD',
    volume: '6093',
    meta: {
      faq: 'http://monero.org/faq/',
      blog: 'https://getmonero.org/blog/',
      icon: 'XMR',
      forum: 'https://forum.getmonero.org/',
      github: 'https://github.com/monero-project/monero',
      reddit: 'https://www.reddit.com/r/Monero/',
      devDocs: 'http://monero.readthedocs.io/',
      roadmap: 'https://getmonero.org/resources/roadmap/',
      summary:
        "With Monero's sophisticated privacy-centric technology, you get all of the security benefits of the blockchain without any of the privacy trade-offs. By taking advantage of ring signatures, Monero makes it ambiguous which funds have been spent, and thus extremely unlikely that a transaction could be linked to particular user.",
      explorer: 'http://moneroblocks.info/',
      website2: '',
      explorer2: 'http://chainradar.com/xmr/blocks',
      wikipedia: 'https://en.wikipedia.org/wiki/Monero_(cryptocurrency)',
      foundation: '',
      whitepaper: '',
      eveningstarUrl: 'https://eveningstar.io/asset/monero/',
      walletDownload: 'https://getmonero.org/downloads/',
      teamInformation: 'https://getmonero.org/knowledge-base/people',
      name: 'Monero'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'NEO',
    name: 'NEO',
    id: 'NEOUSD',
    volume: '335252',
    meta: {
      faq: '',
      blog: 'https://neo.org/en-US/Blog/Details/41',
      icon: 'NEO',
      forum: '',
      github: 'https://github.com/AntShares',
      reddit: 'https://www.reddit.com/r/neo/',
      devDocs: 'https://github.com/neo-project/neo/wiki/Whitepaper-1.1',
      roadmap: 'https://neo.org/en-US/Blog/Details/28',
      summary:
        "As China's first ever original and open source public chain project, NEO serves as a smart assets platform that accepts advanced programing languages.",
      explorer: 'http://antcha.in/',
      website2: '',
      explorer2: '',
      wikipedia: '',
      foundation: '',
      whitepaper: 'http://docs.neo.org/en-us/index.html',
      eveningstarUrl: 'https://eveningstar.io/asset/neo/',
      walletDownload: 'https://neo.org/en-us/download',
      teamInformation: '',
      name: 'NEO'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'GNO',
    name: 'Gnosis',
    id: 'GNOUSD',
    volume: '35',
    meta: {
      faq: 'https://forum.gnosis.pm/t/gnosis-faq/259',
      blog: 'https://blog.gnosis.pm/',
      icon: 'GNO',
      forum: 'https://forum.gnosis.pm/',
      github: 'https://github.com/ConsenSys/gnosis-contracts',
      reddit: 'https://www.reddit.com/r/gnosisPM/',
      devDocs: '',
      roadmap: 'https://gnosis.pm/timeline',
      summary: '',
      explorer: 'https://etherscan.io/token/Gnosis',
      website2: '',
      explorer2: '',
      wikipedia: 'https://en.wikipedia.org/wiki/Gnosis',
      foundation: '',
      whitepaper:
        'https://gnosis.pm/resources/default/pdf/gnosis_whitepaper.pdf',
      eveningstarUrl: 'https://eveningstar.io/asset/gnosis-gno/',
      walletDownload: '',
      teamInformation: 'https://gnosis.pm/timeline',
      name: 'Gnosis / US Dollar'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'OMG',
    name: 'OmiseGO',
    id: 'OMGUSD',
    volume: '211872',
    meta: {
      faq: 'https://www.omise.co/support',
      blog: 'https://www.omise.co/blog',
      icon: 'OMG',
      forum: 'https://www.cryptocompare.com/coins/omg/forum',
      github: 'https://github.com/omise',
      reddit: 'https://www.reddit.com/r/omise_go/',
      devDocs: 'https://www.omise.co/docs',
      roadmap: '',
      summary:
        'OmiseGo (OMG) is the token of the OmiseGo platform which pays for transaction fees and can be used in its various financial services.',
      explorer: 'https://etherscan.io/token/OmiseGo',
      website2: '',
      explorer2:
        'https://ethplorer.io/address/0xd26114cd6ee289accf82350c8d8487fedb8a0c07',
      wikipedia: '',
      foundation: '',
      whitepaper: 'https://cdn.omise.co/omg/whitepaper.pdf',
      eveningstarUrl: 'https://eveningstar.io/asset/omisego/',
      walletDownload: '',
      teamInformation: 'https://www.omise.co/team',
      name: 'OmiseGO'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'QTM',
    name: 'Qtum',
    id: 'QTMUSD',
    volume: '8004',
    meta: {
      faq: 'https://qtum.org/en/general-faq',
      blog: 'https://qtum.org/en/blog',
      icon: 'QTM',
      forum: 'https://forum.qtum.org/',
      github: 'https://github.com/qtumproject',
      reddit: 'https://www.reddit.com/r/Qtum/',
      devDocs: 'https://github.com/qtumproject/qtum/releases',
      roadmap: 'https://qtum.org/en/crowdsale',
      summary:
        'Qtum (QTUM) is the native token of the Qtum ecosystem and blockchain.',
      explorer: 'https://etherscan.io/token/Qtum',
      website2: '',
      explorer2: '',
      wikipedia: '',
      foundation:
        'https://qtum.org/en//the-qtum-foundation-governance-structure',
      whitepaper: 'https://qtum.org/en/white-papers',
      eveningstarUrl: 'https://eveningstar.io/asset/qtum/',
      walletDownload: '',
      teamInformation: 'https://qtum.org/en/team',
      name: 'Qtum'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'SAN',
    name: 'Santiment Network Token',
    id: 'SANUSD',
    volume: '54948',
    meta: {
      faq: '',
      blog: '',
      icon: 'SAN',
      forum: '',
      github: '',
      reddit: '',
      devDocs: '',
      roadmap: '',
      summary: '',
      explorer: '',
      website2: '',
      explorer2: '',
      wikipedia: '',
      foundation: '',
      whitepaper: '',
      eveningstarUrl: '',
      walletDownload: '',
      teamInformation: '',
      name: 'Santiment Network Token'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'USDT',
    name: 'Tether',
    id: 'USDTUSD',
    volume: '2224467',
    meta: {
      faq: '',
      blog: '',
      icon: 'USDT',
      forum: '',
      github: '',
      reddit: '',
      devDocs: '',
      roadmap: '',
      summary: '',
      explorer: '',
      website2: '',
      explorer2: '',
      wikipedia: '',
      foundation: '',
      whitepaper: '',
      eveningstarUrl: '',
      walletDownload: '',
      teamInformation: '',
      name: 'Tether'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'ZEC',
    name: 'Zcash',
    id: 'ZECUSD',
    volume: '17388',
    meta: {
      faq: 'https://z.cash/support/faq.html',
      blog: 'https://z.cash/blog/',
      icon: 'ZEC',
      forum: 'https://forum.z.cash/',
      github: 'https://github.com/zcash/zcash',
      reddit: 'https://www.reddit.com/r/zec/',
      devDocs: 'https://github.com/zcash/zcash-docs',
      roadmap: 'https://z.cash/blog/zcash-launch-and-roadmap.html',
      summary:
        'Zcash is the first open, permissionless cryptocurrency that can fully protect the privacy of transactions using zero-knowledge cryptography.',
      explorer: 'https://explorer.zcha.in/',
      website2: '',
      explorer2: '',
      wikipedia: 'https://en.wikipedia.org/wiki/Zcash',
      foundation: 'https://z.cash/blog/announcing-the-zcash-foundation.html',
      whitepaper:
        'http://zerocash-project.org/media/pdf/zerocash-extended-20140518.pdf',
      eveningstarUrl: 'https://eveningstar.io/asset/zcash/',
      walletDownload: 'https://z.cash/download.html',
      teamInformation: 'https://z.cash/team.html',
      name: 'Zcash'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'BTC',
    name: 'Bitcoin',
    id: 'BTCUSD',
    volume: '9646',
    meta: {
      faq: 'https://bitcoin.org/en/faq',
      blog: 'https://bitcoin.org/en/blog',
      icon: 'BTC',
      forum: 'https://bitcointalk.org/',
      github: 'https://github.com/bitcoin/bitcoin',
      reddit: 'https://www.reddit.com/r/Bitcoin/',
      devDocs: 'https://bitcoin.org/en/developer-documentation',
      roadmap:
        'https://bitcoincore.org/en/2017/03/23/schnorr-signature-aggregation/',
      summary:
        'Bitcoin uses peer-to-peer technology to operate with no central authority or banks; managing transactions and the issuing of bitcoins is carried out collectively by the network.',
      explorer: 'http://blockchain.info/',
      website2: 'https://www.bitcoin.com/',
      explorer2: 'https://blockexplorer.com/',
      wikipedia: 'https://en.wikipedia.org/wiki/Bitcoin',
      foundation: 'https://bitcoinfoundation.org/',
      whitepaper: 'https://bitcoin.org/bitcoin.pdf',
      eveningstarUrl: 'https://eveningstar.io/asset/bitcoin/',
      walletDownload: 'https://bitcoin.org/en/download',
      teamInformation: '',
      name: 'Bitcoin'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: true
  },
  {
    instrumentId: 'ETH',
    name: 'Ethereum',
    id: 'ETHUSD',
    volume: '37078',
    meta: {
      faq: 'https://www.ethereum.org/ether',
      blog: 'http://blog.ethereum.org/',
      icon: 'ETH',
      forum: 'https://forum.ethereum.org/',
      github: 'https://github.com/ethereum/mist/releases',
      reddit: 'https://www.reddit.com/r/ethereum/',
      devDocs: '',
      roadmap: 'http://www.ethdocs.org/en/latest/',
      summary:
        'Ethereum is a decentralized platform that runs smart contracts: applications that run exactly as programmed without any possibility of downtime, censorship, fraud or third party interference.',
      explorer: 'https://live.ether.camp/',
      website2: 'https://www.ethereum.org/foundation',
      explorer2: 'https://etherscan.io/',
      wikipedia: 'https://en.wikipedia.org/wiki/Ethereum',
      foundation: 'https://www.ethereum.org/foundation',
      whitepaper: 'https://github.com/ethereum/wiki/wiki/White-Paper',
      eveningstarUrl: 'https://eveningstar.io/asset/ethereum/',
      walletDownload: 'https://geth.ethereum.org/downloads/',
      teamInformation: 'https://www.ethereum.org/foundation',
      name: 'Ethereum'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: true
  },
  {
    instrumentId: 'XRP',
    name: 'Ripple',
    id: 'XRPUSD',
    volume: '12204352',
    meta: {
      faq: 'https://www.ripplecrew.com/pages/faq',
      blog: 'http://rippleit.com/blog/',
      icon: 'XRP',
      forum: 'http://www.xrpchat.com/',
      github: 'https://github.com/ripple',
      reddit: 'https://www.reddit.com/r/Ripple/',
      devDocs: 'https://ripple.moe/doc',
      roadmap: 'https://trello.com/b/5nQ1mdzt/ledger-roadmap',
      summary:
        'Using Ripple, banks can meet growing demands for faster, low-cost, on-demand global payment services for any payment size. The result: new revenue opportunities, lower processing costs, and better overall customer experiences.',
      explorer: 'https://ripple.com/graph',
      website2: '',
      explorer2: 'https://bithomp.com/explorer/',
      wikipedia: 'https://en.wikipedia.org/wiki/Ripple_(company)',
      foundation: 'http://theripplefoundation.org/',
      whitepaper: 'https://ripple.com/files/ripple_consensus_whitepaper.pdf',
      eveningstarUrl: 'https://eveningstar.io/asset/ripple/',
      walletDownload: '',
      teamInformation: 'https://ripple.com/company',
      name: 'Ripple'
    },
    currencyCode: 'USD',
    precision: 5,
    sharePrecision: 8,
    scale: 1,
    isTradable: true
  },
  {
    instrumentId: 'IOT',
    name: 'IOTA',
    id: 'IOTEUR',
    volume: '164125',
    meta: {
      faq: 'https://learn.iota.org/faqs',
      blog: 'https://blog.iota.org/',
      icon: 'IOT',
      forum: 'https://forum.iota.org/',
      github: 'https://github.com/iotaledger',
      reddit: 'https://www.reddit.com/r/Iota/',
      devDocs: 'https://iota.readme.io/docs',
      roadmap: 'https://blog.iota.org/iota-development-roadmap-74741f37ed01',
      summary:
        'IOTA makes every technological resource a potential service to be traded on an open market in real time, with no fees. In this new autonomous Machine Economy IOTA will be the backbone. The Tangle ledger is able to settle transactions with zero fees so devices can trade exact amounts of resources on-demand, as well as store data from sensors and dataloggers.',
      explorer: 'http://www.iota.tips/',
      website2: '',
      explorer2: '',
      wikipedia: 'https://en.wikipedia.org/wiki/Iota',
      foundation: 'http://iotasupport.com/foundation.shtml',
      whitepaper: 'https://iota.org/IOTA_Whitepaper.pdf',
      eveningstarUrl: 'https://eveningstar.io/asset/iota/',
      walletDownload: '',
      teamInformation: 'http://iotasupport.com/foundation.shtml',
      name: 'IOTA'
    },
    currencyCode: 'EUR',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  },
  {
    instrumentId: 'XLM',
    name: 'Stellar Lumens',
    id: 'XLMUSD',
    volume: '5746357',
    meta: {
      faq: 'https://www.stellar.org/faq/',
      blog: 'https://www.stellar.org/blog/',
      icon: 'XLM',
      forum: 'https://mystellar.org/',
      github: 'https://github.com/stellar',
      reddit: 'https://www.reddit.com/r/Stellar/',
      devDocs: 'https://www.stellar.org/developers/',
      roadmap: 'https://www.stellar.org/blog/roadmap/',
      summary:
        'Stellar Lumens (XLM) is the native asset token that is used to pay transaction fees and facilitate trades between two asset pairs if needed.',
      explorer: 'https://www.stellar.org/stats/',
      website2: '',
      explorer2: '',
      wikipedia: 'https://en.wikipedia.org/wiki/Stellar_(payment_network)',
      foundation: '',
      whitepaper:
        'https://www.stellar.org/papers/stellar-consensus-protocol.pdf',
      eveningstarUrl: 'https://eveningstar.io/asset/stellar/',
      walletDownload: 'https://www.stellar.org/about/directory#wallets',
      teamInformation: 'https://www.stellar.org/about/',
      name: 'Stellar Lumens'
    },
    currencyCode: 'USD',
    precision: 2,
    sharePrecision: 8,
    scale: 1,
    isTradable: false
  }
]
